//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareWebClient.careService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RegDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool RegStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool RegStatus {
            get {
                return this.RegStatusField;
            }
            set {
                if ((this.RegStatusField.Equals(value) != true)) {
                    this.RegStatusField = value;
                    this.RaisePropertyChanged("RegStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RegMessage {
            get {
                return this.RegMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.RegMessageField, value) != true)) {
                    this.RegMessageField = value;
                    this.RaisePropertyChanged("RegMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staffs", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Staffs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.Guid> CareStaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffLoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffRatingsField;
        
        private System.Nullable<System.DateTime> DateRegisteredField;
        
        private System.Nullable<bool> CareStaffEmploymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareStaffEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> CareStaffId {
            get {
                return this.CareStaffIdField;
            }
            set {
                if ((this.CareStaffIdField.Equals(value) != true)) {
                    this.CareStaffIdField = value;
                    this.RaisePropertyChanged("CareStaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CareStaffLoginName {
            get {
                return this.CareStaffLoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffLoginNameField, value) != true)) {
                    this.CareStaffLoginNameField = value;
                    this.RaisePropertyChanged("CareStaffLoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CareStaffName {
            get {
                return this.CareStaffNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffNameField, value) != true)) {
                    this.CareStaffNameField = value;
                    this.RaisePropertyChanged("CareStaffName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CareStaffContactNumber {
            get {
                return this.CareStaffContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffContactNumberField, value) != true)) {
                    this.CareStaffContactNumberField = value;
                    this.RaisePropertyChanged("CareStaffContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CareStaffRatings {
            get {
                return this.CareStaffRatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffRatingsField, value) != true)) {
                    this.CareStaffRatingsField = value;
                    this.RaisePropertyChanged("CareStaffRatings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> CareStaffEmploymentStatus {
            get {
                return this.CareStaffEmploymentStatusField;
            }
            set {
                if ((this.CareStaffEmploymentStatusField.Equals(value) != true)) {
                    this.CareStaffEmploymentStatusField = value;
                    this.RaisePropertyChanged("CareStaffEmploymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CareStaffPassword {
            get {
                return this.CareStaffPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffPasswordField, value) != true)) {
                    this.CareStaffPasswordField = value;
                    this.RaisePropertyChanged("CareStaffPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CareStaffEmail {
            get {
                return this.CareStaffEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CareStaffEmailField, value) != true)) {
                    this.CareStaffEmailField = value;
                    this.RaisePropertyChanged("CareStaffEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid CareCenterIdField;
        
        private bool ValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CenterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CenterLocationField;
        
        private System.Nullable<bool> SubscriptionStatusField;
        
        private System.Nullable<bool> ActivateDeactivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffStrengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CenterEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] LogoField;
        
        private System.Nullable<System.DateTime> LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CareWebClient.careService.Payment[] TransDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid CareCenterId {
            get {
                return this.CareCenterIdField;
            }
            set {
                if ((this.CareCenterIdField.Equals(value) != true)) {
                    this.CareCenterIdField = value;
                    this.RaisePropertyChanged("CareCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Valid {
            get {
                return this.ValidField;
            }
            set {
                if ((this.ValidField.Equals(value) != true)) {
                    this.ValidField = value;
                    this.RaisePropertyChanged("Valid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LoginMessage {
            get {
                return this.LoginMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginMessageField, value) != true)) {
                    this.LoginMessageField = value;
                    this.RaisePropertyChanged("LoginMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CenterName {
            get {
                return this.CenterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CenterNameField, value) != true)) {
                    this.CenterNameField = value;
                    this.RaisePropertyChanged("CenterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CenterLocation {
            get {
                return this.CenterLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CenterLocationField, value) != true)) {
                    this.CenterLocationField = value;
                    this.RaisePropertyChanged("CenterLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<bool> SubscriptionStatus {
            get {
                return this.SubscriptionStatusField;
            }
            set {
                if ((this.SubscriptionStatusField.Equals(value) != true)) {
                    this.SubscriptionStatusField = value;
                    this.RaisePropertyChanged("SubscriptionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> ActivateDeactivate {
            get {
                return this.ActivateDeactivateField;
            }
            set {
                if ((this.ActivateDeactivateField.Equals(value) != true)) {
                    this.ActivateDeactivateField = value;
                    this.RaisePropertyChanged("ActivateDeactivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StaffStrength {
            get {
                return this.StaffStrengthField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffStrengthField, value) != true)) {
                    this.StaffStrengthField = value;
                    this.RaisePropertyChanged("StaffStrength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FolderId {
            get {
                return this.FolderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderIdField, value) != true)) {
                    this.FolderIdField = value;
                    this.RaisePropertyChanged("FolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CenterEmail {
            get {
                return this.CenterEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CenterEmailField, value) != true)) {
                    this.CenterEmailField = value;
                    this.RaisePropertyChanged("CenterEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ImgPath {
            get {
                return this.ImgPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgPathField, value) != true)) {
                    this.ImgPathField = value;
                    this.RaisePropertyChanged("ImgPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public byte[] Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public CareWebClient.careService.Payment[] TransDetails {
            get {
                return this.TransDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransDetailsField, value) != true)) {
                    this.TransDetailsField = value;
                    this.RaisePropertyChanged("TransDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDescriptionField;
        
        private System.Nullable<decimal> PaymentInvoicedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptNoField;
        
        private System.Nullable<decimal> PaymentMadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymenTypeField;
        
        private System.Nullable<System.DateTime> PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PaymentDescription {
            get {
                return this.PaymentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDescriptionField, value) != true)) {
                    this.PaymentDescriptionField = value;
                    this.RaisePropertyChanged("PaymentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> PaymentInvoiced {
            get {
                return this.PaymentInvoicedField;
            }
            set {
                if ((this.PaymentInvoicedField.Equals(value) != true)) {
                    this.PaymentInvoicedField = value;
                    this.RaisePropertyChanged("PaymentInvoiced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiptNo {
            get {
                return this.ReceiptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptNoField, value) != true)) {
                    this.ReceiptNoField = value;
                    this.RaisePropertyChanged("ReceiptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> PaymentMade {
            get {
                return this.PaymentMadeField;
            }
            set {
                if ((this.PaymentMadeField.Equals(value) != true)) {
                    this.PaymentMadeField = value;
                    this.RaisePropertyChanged("PaymentMade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymenType {
            get {
                return this.PaymenTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymenTypeField, value) != true)) {
                    this.PaymenTypeField = value;
                    this.RaisePropertyChanged("PaymenType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UpdateDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool UpdateStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UpdateStatus {
            get {
                return this.UpdateStatusField;
            }
            set {
                if ((this.UpdateStatusField.Equals(value) != true)) {
                    this.UpdateStatusField = value;
                    this.RaisePropertyChanged("UpdateStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UpdateMessage {
            get {
                return this.UpdateMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateMessageField, value) != true)) {
                    this.UpdateMessageField = value;
                    this.RaisePropertyChanged("UpdateMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CareKiddieDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CareKiddieDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid CareCenterIdField;
        
        private System.Guid CarekiddieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieOtherNameField;
        
        private System.Nullable<System.DateTime> CarekiddieDobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieBloodGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieGenotypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddieGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarekiddiePhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CareWebClient.careService.Payment[] PaymentDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CareWebClient.careService.Parent ParentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CareWebClient.careService.Activities[] ActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CareWebClient.careService.Pictures[] PicturesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid CareCenterId {
            get {
                return this.CareCenterIdField;
            }
            set {
                if ((this.CareCenterIdField.Equals(value) != true)) {
                    this.CareCenterIdField = value;
                    this.RaisePropertyChanged("CareCenterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid CarekiddieId {
            get {
                return this.CarekiddieIdField;
            }
            set {
                if ((this.CarekiddieIdField.Equals(value) != true)) {
                    this.CarekiddieIdField = value;
                    this.RaisePropertyChanged("CarekiddieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarekiddieLastName {
            get {
                return this.CarekiddieLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieLastNameField, value) != true)) {
                    this.CarekiddieLastNameField = value;
                    this.RaisePropertyChanged("CarekiddieLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CarekiddieFirstName {
            get {
                return this.CarekiddieFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieFirstNameField, value) != true)) {
                    this.CarekiddieFirstNameField = value;
                    this.RaisePropertyChanged("CarekiddieFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CarekiddieOtherName {
            get {
                return this.CarekiddieOtherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieOtherNameField, value) != true)) {
                    this.CarekiddieOtherNameField = value;
                    this.RaisePropertyChanged("CarekiddieOtherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> CarekiddieDob {
            get {
                return this.CarekiddieDobField;
            }
            set {
                if ((this.CarekiddieDobField.Equals(value) != true)) {
                    this.CarekiddieDobField = value;
                    this.RaisePropertyChanged("CarekiddieDob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CarekiddieBloodGroup {
            get {
                return this.CarekiddieBloodGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieBloodGroupField, value) != true)) {
                    this.CarekiddieBloodGroupField = value;
                    this.RaisePropertyChanged("CarekiddieBloodGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CarekiddieGenotype {
            get {
                return this.CarekiddieGenotypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieGenotypeField, value) != true)) {
                    this.CarekiddieGenotypeField = value;
                    this.RaisePropertyChanged("CarekiddieGenotype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CarekiddieGender {
            get {
                return this.CarekiddieGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddieGenderField, value) != true)) {
                    this.CarekiddieGenderField = value;
                    this.RaisePropertyChanged("CarekiddieGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CarekiddiePhotoPath {
            get {
                return this.CarekiddiePhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.CarekiddiePhotoPathField, value) != true)) {
                    this.CarekiddiePhotoPathField = value;
                    this.RaisePropertyChanged("CarekiddiePhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CareWebClient.careService.Payment[] PaymentDetails {
            get {
                return this.PaymentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDetailsField, value) != true)) {
                    this.PaymentDetailsField = value;
                    this.RaisePropertyChanged("PaymentDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CareWebClient.careService.Parent Parents {
            get {
                return this.ParentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentsField, value) != true)) {
                    this.ParentsField = value;
                    this.RaisePropertyChanged("Parents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public CareWebClient.careService.Activities[] Activities {
            get {
                return this.ActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivitiesField, value) != true)) {
                    this.ActivitiesField = value;
                    this.RaisePropertyChanged("Activities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public CareWebClient.careService.Pictures[] Pictures {
            get {
                return this.PicturesField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturesField, value) != true)) {
                    this.PicturesField = value;
                    this.RaisePropertyChanged("Pictures");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Parent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentLoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ParentLoginId {
            get {
                return this.ParentLoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentLoginIdField, value) != true)) {
                    this.ParentLoginIdField = value;
                    this.RaisePropertyChanged("ParentLoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ParentFullName {
            get {
                return this.ParentFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentFullNameField, value) != true)) {
                    this.ParentFullNameField = value;
                    this.RaisePropertyChanged("ParentFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ParentContactNo {
            get {
                return this.ParentContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentContactNoField, value) != true)) {
                    this.ParentContactNoField = value;
                    this.RaisePropertyChanged("ParentContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ParentEmail {
            get {
                return this.ParentEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentEmailField, value) != true)) {
                    this.ParentEmailField = value;
                    this.RaisePropertyChanged("ParentEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activities", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Activities : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.Guid> ActivityIdField;
        
        private System.Guid KiddiesActivityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KiddiesActivityNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KiddiesActivityImagePathField;
        
        private System.Nullable<System.DateTime> KiddiesActivityDateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityIconPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.Guid> ActivityId {
            get {
                return this.ActivityIdField;
            }
            set {
                if ((this.ActivityIdField.Equals(value) != true)) {
                    this.ActivityIdField = value;
                    this.RaisePropertyChanged("ActivityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid KiddiesActivityId {
            get {
                return this.KiddiesActivityIdField;
            }
            set {
                if ((this.KiddiesActivityIdField.Equals(value) != true)) {
                    this.KiddiesActivityIdField = value;
                    this.RaisePropertyChanged("KiddiesActivityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KiddiesActivityNotes {
            get {
                return this.KiddiesActivityNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.KiddiesActivityNotesField, value) != true)) {
                    this.KiddiesActivityNotesField = value;
                    this.RaisePropertyChanged("KiddiesActivityNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string KiddiesActivityImagePath {
            get {
                return this.KiddiesActivityImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.KiddiesActivityImagePathField, value) != true)) {
                    this.KiddiesActivityImagePathField = value;
                    this.RaisePropertyChanged("KiddiesActivityImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> KiddiesActivityDateUpdated {
            get {
                return this.KiddiesActivityDateUpdatedField;
            }
            set {
                if ((this.KiddiesActivityDateUpdatedField.Equals(value) != true)) {
                    this.KiddiesActivityDateUpdatedField = value;
                    this.RaisePropertyChanged("KiddiesActivityDateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ActivityTitle {
            get {
                return this.ActivityTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityTitleField, value) != true)) {
                    this.ActivityTitleField = value;
                    this.RaisePropertyChanged("ActivityTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ActivityIconPath {
            get {
                return this.ActivityIconPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityIconPathField, value) != true)) {
                    this.ActivityIconPathField = value;
                    this.RaisePropertyChanged("ActivityIconPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pictures", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pictures : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid PhotoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoDescriptionField;
        
        private System.Nullable<System.DateTime> DateCapturedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid PhotoId {
            get {
                return this.PhotoIdField;
            }
            set {
                if ((this.PhotoIdField.Equals(value) != true)) {
                    this.PhotoIdField = value;
                    this.RaisePropertyChanged("PhotoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhotoDescription {
            get {
                return this.PhotoDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoDescriptionField, value) != true)) {
                    this.PhotoDescriptionField = value;
                    this.RaisePropertyChanged("PhotoDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> DateCaptured {
            get {
                return this.DateCapturedField;
            }
            set {
                if ((this.DateCapturedField.Equals(value) != true)) {
                    this.DateCapturedField = value;
                    this.RaisePropertyChanged("DateCaptured");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="careService.CareService1Soap")]
    public interface CareService1Soap {
        
        // CODEGEN: Generating message contract since element name careCenterLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        CareWebClient.careService.RegisterResponse Register(CareWebClient.careService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.RegisterResponse> RegisterAsync(CareWebClient.careService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name newStaff from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterStaff", ReplyAction="*")]
        CareWebClient.careService.RegisterStaffResponse RegisterStaff(CareWebClient.careService.RegisterStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.RegisterStaffResponse> RegisterStaffAsync(CareWebClient.careService.RegisterStaffRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWeb", ReplyAction="*")]
        CareWebClient.careService.AuthenticateUserWebResponse AuthenticateUserWeb(CareWebClient.careService.AuthenticateUserWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserWebResponse> AuthenticateUserWebAsync(CareWebClient.careService.AuthenticateUserWebRequest request);
        
        // CODEGEN: Generating message contract since element name profileChangesDetails from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        CareWebClient.careService.UpdateProfileResponse UpdateProfile(CareWebClient.careService.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.UpdateProfileResponse> UpdateProfileAsync(CareWebClient.careService.UpdateProfileRequest request);
        
        // CODEGEN: Generating message contract since element name GetCareCenterKiddiesDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareCenterKiddiesDetails", ReplyAction="*")]
        CareWebClient.careService.GetCareCenterKiddiesDetailsResponse GetCareCenterKiddiesDetails(CareWebClient.careService.GetCareCenterKiddiesDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareCenterKiddiesDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterKiddiesDetailsResponse> GetCareCenterKiddiesDetailsAsync(CareWebClient.careService.GetCareCenterKiddiesDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCareCenterStaffsDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareCenterStaffsDetails", ReplyAction="*")]
        CareWebClient.careService.GetCareCenterStaffsDetailsResponse GetCareCenterStaffsDetails(CareWebClient.careService.GetCareCenterStaffsDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareCenterStaffsDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterStaffsDetailsResponse> GetCareCenterStaffsDetailsAsync(CareWebClient.careService.GetCareCenterStaffsDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserApp", ReplyAction="*")]
        CareWebClient.careService.AuthenticateUserAppResponse AuthenticateUserApp(CareWebClient.careService.AuthenticateUserAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUserApp", ReplyAction="*")]
        System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserAppResponse> AuthenticateUserAppAsync(CareWebClient.careService.AuthenticateUserAppRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(CareWebClient.careService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string careCenterLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string careCenterPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string careCenterEmail;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string careCenterLoginName, string careCenterPassword, string careCenterEmail) {
            this.careCenterLoginName = careCenterLoginName;
            this.careCenterPassword = careCenterPassword;
            this.careCenterEmail = careCenterEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(CareWebClient.careService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.RegDetails RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(CareWebClient.careService.RegDetails RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterStaff", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.RegisterStaffRequestBody Body;
        
        public RegisterStaffRequest() {
        }
        
        public RegisterStaffRequest(CareWebClient.careService.RegisterStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.Staffs newStaff;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid careCenterId;
        
        public RegisterStaffRequestBody() {
        }
        
        public RegisterStaffRequestBody(CareWebClient.careService.Staffs newStaff, System.Guid careCenterId) {
            this.newStaff = newStaff;
            this.careCenterId = careCenterId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.RegisterStaffResponseBody Body;
        
        public RegisterStaffResponse() {
        }
        
        public RegisterStaffResponse(CareWebClient.careService.RegisterStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.RegDetails RegisterStaffResult;
        
        public RegisterStaffResponseBody() {
        }
        
        public RegisterStaffResponseBody(CareWebClient.careService.RegDetails RegisterStaffResult) {
            this.RegisterStaffResult = RegisterStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWeb", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.AuthenticateUserWebRequestBody Body;
        
        public AuthenticateUserWebRequest() {
        }
        
        public AuthenticateUserWebRequest(CareWebClient.careService.AuthenticateUserWebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWebRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateUserWebRequestBody() {
        }
        
        public AuthenticateUserWebRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserWebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserWebResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.AuthenticateUserWebResponseBody Body;
        
        public AuthenticateUserWebResponse() {
        }
        
        public AuthenticateUserWebResponse(CareWebClient.careService.AuthenticateUserWebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserWebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.LoginDetails AuthenticateUserWebResult;
        
        public AuthenticateUserWebResponseBody() {
        }
        
        public AuthenticateUserWebResponseBody(CareWebClient.careService.LoginDetails AuthenticateUserWebResult) {
            this.AuthenticateUserWebResult = AuthenticateUserWebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfile", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.UpdateProfileRequestBody Body;
        
        public UpdateProfileRequest() {
        }
        
        public UpdateProfileRequest(CareWebClient.careService.UpdateProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.LoginDetails profileChangesDetails;
        
        public UpdateProfileRequestBody() {
        }
        
        public UpdateProfileRequestBody(CareWebClient.careService.LoginDetails profileChangesDetails) {
            this.profileChangesDetails = profileChangesDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.UpdateProfileResponseBody Body;
        
        public UpdateProfileResponse() {
        }
        
        public UpdateProfileResponse(CareWebClient.careService.UpdateProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.UpdateDetails UpdateProfileResult;
        
        public UpdateProfileResponseBody() {
        }
        
        public UpdateProfileResponseBody(CareWebClient.careService.UpdateDetails UpdateProfileResult) {
            this.UpdateProfileResult = UpdateProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCareCenterKiddiesDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCareCenterKiddiesDetails", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.GetCareCenterKiddiesDetailsRequestBody Body;
        
        public GetCareCenterKiddiesDetailsRequest() {
        }
        
        public GetCareCenterKiddiesDetailsRequest(CareWebClient.careService.GetCareCenterKiddiesDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCareCenterKiddiesDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid centerId;
        
        public GetCareCenterKiddiesDetailsRequestBody() {
        }
        
        public GetCareCenterKiddiesDetailsRequestBody(System.Guid centerId) {
            this.centerId = centerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCareCenterKiddiesDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCareCenterKiddiesDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.GetCareCenterKiddiesDetailsResponseBody Body;
        
        public GetCareCenterKiddiesDetailsResponse() {
        }
        
        public GetCareCenterKiddiesDetailsResponse(CareWebClient.careService.GetCareCenterKiddiesDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCareCenterKiddiesDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.CareKiddieDetails[] GetCareCenterKiddiesDetailsResult;
        
        public GetCareCenterKiddiesDetailsResponseBody() {
        }
        
        public GetCareCenterKiddiesDetailsResponseBody(CareWebClient.careService.CareKiddieDetails[] GetCareCenterKiddiesDetailsResult) {
            this.GetCareCenterKiddiesDetailsResult = GetCareCenterKiddiesDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCareCenterStaffsDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCareCenterStaffsDetails", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.GetCareCenterStaffsDetailsRequestBody Body;
        
        public GetCareCenterStaffsDetailsRequest() {
        }
        
        public GetCareCenterStaffsDetailsRequest(CareWebClient.careService.GetCareCenterStaffsDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCareCenterStaffsDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid centerId;
        
        public GetCareCenterStaffsDetailsRequestBody() {
        }
        
        public GetCareCenterStaffsDetailsRequestBody(System.Guid centerId) {
            this.centerId = centerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCareCenterStaffsDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCareCenterStaffsDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.GetCareCenterStaffsDetailsResponseBody Body;
        
        public GetCareCenterStaffsDetailsResponse() {
        }
        
        public GetCareCenterStaffsDetailsResponse(CareWebClient.careService.GetCareCenterStaffsDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCareCenterStaffsDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CareWebClient.careService.Staffs[] GetCareCenterStaffsDetailsResult;
        
        public GetCareCenterStaffsDetailsResponseBody() {
        }
        
        public GetCareCenterStaffsDetailsResponseBody(CareWebClient.careService.Staffs[] GetCareCenterStaffsDetailsResult) {
            this.GetCareCenterStaffsDetailsResult = GetCareCenterStaffsDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserApp", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.AuthenticateUserAppRequestBody Body;
        
        public AuthenticateUserAppRequest() {
        }
        
        public AuthenticateUserAppRequest(CareWebClient.careService.AuthenticateUserAppRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserAppRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        public AuthenticateUserAppRequestBody() {
        }
        
        public AuthenticateUserAppRequestBody(string name, string password, string type) {
            this.name = name;
            this.password = password;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserAppResponse", Namespace="http://tempuri.org/", Order=0)]
        public CareWebClient.careService.AuthenticateUserAppResponseBody Body;
        
        public AuthenticateUserAppResponse() {
        }
        
        public AuthenticateUserAppResponse(CareWebClient.careService.AuthenticateUserAppResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AuthenticateUserAppResponseBody {
        
        public AuthenticateUserAppResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CareService1SoapChannel : CareWebClient.careService.CareService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CareService1SoapClient : System.ServiceModel.ClientBase<CareWebClient.careService.CareService1Soap>, CareWebClient.careService.CareService1Soap {
        
        public CareService1SoapClient() {
        }
        
        public CareService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CareService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CareService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CareService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.RegisterResponse CareWebClient.careService.CareService1Soap.Register(CareWebClient.careService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public CareWebClient.careService.RegDetails Register(string careCenterLoginName, string careCenterPassword, string careCenterEmail) {
            CareWebClient.careService.RegisterRequest inValue = new CareWebClient.careService.RegisterRequest();
            inValue.Body = new CareWebClient.careService.RegisterRequestBody();
            inValue.Body.careCenterLoginName = careCenterLoginName;
            inValue.Body.careCenterPassword = careCenterPassword;
            inValue.Body.careCenterEmail = careCenterEmail;
            CareWebClient.careService.RegisterResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.RegisterResponse> CareWebClient.careService.CareService1Soap.RegisterAsync(CareWebClient.careService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.RegisterResponse> RegisterAsync(string careCenterLoginName, string careCenterPassword, string careCenterEmail) {
            CareWebClient.careService.RegisterRequest inValue = new CareWebClient.careService.RegisterRequest();
            inValue.Body = new CareWebClient.careService.RegisterRequestBody();
            inValue.Body.careCenterLoginName = careCenterLoginName;
            inValue.Body.careCenterPassword = careCenterPassword;
            inValue.Body.careCenterEmail = careCenterEmail;
            return ((CareWebClient.careService.CareService1Soap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.RegisterStaffResponse CareWebClient.careService.CareService1Soap.RegisterStaff(CareWebClient.careService.RegisterStaffRequest request) {
            return base.Channel.RegisterStaff(request);
        }
        
        public CareWebClient.careService.RegDetails RegisterStaff(CareWebClient.careService.Staffs newStaff, System.Guid careCenterId) {
            CareWebClient.careService.RegisterStaffRequest inValue = new CareWebClient.careService.RegisterStaffRequest();
            inValue.Body = new CareWebClient.careService.RegisterStaffRequestBody();
            inValue.Body.newStaff = newStaff;
            inValue.Body.careCenterId = careCenterId;
            CareWebClient.careService.RegisterStaffResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).RegisterStaff(inValue);
            return retVal.Body.RegisterStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.RegisterStaffResponse> CareWebClient.careService.CareService1Soap.RegisterStaffAsync(CareWebClient.careService.RegisterStaffRequest request) {
            return base.Channel.RegisterStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.RegisterStaffResponse> RegisterStaffAsync(CareWebClient.careService.Staffs newStaff, System.Guid careCenterId) {
            CareWebClient.careService.RegisterStaffRequest inValue = new CareWebClient.careService.RegisterStaffRequest();
            inValue.Body = new CareWebClient.careService.RegisterStaffRequestBody();
            inValue.Body.newStaff = newStaff;
            inValue.Body.careCenterId = careCenterId;
            return ((CareWebClient.careService.CareService1Soap)(this)).RegisterStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.AuthenticateUserWebResponse CareWebClient.careService.CareService1Soap.AuthenticateUserWeb(CareWebClient.careService.AuthenticateUserWebRequest request) {
            return base.Channel.AuthenticateUserWeb(request);
        }
        
        public CareWebClient.careService.LoginDetails AuthenticateUserWeb(string name, string password) {
            CareWebClient.careService.AuthenticateUserWebRequest inValue = new CareWebClient.careService.AuthenticateUserWebRequest();
            inValue.Body = new CareWebClient.careService.AuthenticateUserWebRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            CareWebClient.careService.AuthenticateUserWebResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).AuthenticateUserWeb(inValue);
            return retVal.Body.AuthenticateUserWebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserWebResponse> CareWebClient.careService.CareService1Soap.AuthenticateUserWebAsync(CareWebClient.careService.AuthenticateUserWebRequest request) {
            return base.Channel.AuthenticateUserWebAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserWebResponse> AuthenticateUserWebAsync(string name, string password) {
            CareWebClient.careService.AuthenticateUserWebRequest inValue = new CareWebClient.careService.AuthenticateUserWebRequest();
            inValue.Body = new CareWebClient.careService.AuthenticateUserWebRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((CareWebClient.careService.CareService1Soap)(this)).AuthenticateUserWebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.UpdateProfileResponse CareWebClient.careService.CareService1Soap.UpdateProfile(CareWebClient.careService.UpdateProfileRequest request) {
            return base.Channel.UpdateProfile(request);
        }
        
        public CareWebClient.careService.UpdateDetails UpdateProfile(CareWebClient.careService.LoginDetails profileChangesDetails) {
            CareWebClient.careService.UpdateProfileRequest inValue = new CareWebClient.careService.UpdateProfileRequest();
            inValue.Body = new CareWebClient.careService.UpdateProfileRequestBody();
            inValue.Body.profileChangesDetails = profileChangesDetails;
            CareWebClient.careService.UpdateProfileResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).UpdateProfile(inValue);
            return retVal.Body.UpdateProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.UpdateProfileResponse> CareWebClient.careService.CareService1Soap.UpdateProfileAsync(CareWebClient.careService.UpdateProfileRequest request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.UpdateProfileResponse> UpdateProfileAsync(CareWebClient.careService.LoginDetails profileChangesDetails) {
            CareWebClient.careService.UpdateProfileRequest inValue = new CareWebClient.careService.UpdateProfileRequest();
            inValue.Body = new CareWebClient.careService.UpdateProfileRequestBody();
            inValue.Body.profileChangesDetails = profileChangesDetails;
            return ((CareWebClient.careService.CareService1Soap)(this)).UpdateProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.GetCareCenterKiddiesDetailsResponse CareWebClient.careService.CareService1Soap.GetCareCenterKiddiesDetails(CareWebClient.careService.GetCareCenterKiddiesDetailsRequest request) {
            return base.Channel.GetCareCenterKiddiesDetails(request);
        }
        
        public CareWebClient.careService.CareKiddieDetails[] GetCareCenterKiddiesDetails(System.Guid centerId) {
            CareWebClient.careService.GetCareCenterKiddiesDetailsRequest inValue = new CareWebClient.careService.GetCareCenterKiddiesDetailsRequest();
            inValue.Body = new CareWebClient.careService.GetCareCenterKiddiesDetailsRequestBody();
            inValue.Body.centerId = centerId;
            CareWebClient.careService.GetCareCenterKiddiesDetailsResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).GetCareCenterKiddiesDetails(inValue);
            return retVal.Body.GetCareCenterKiddiesDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterKiddiesDetailsResponse> CareWebClient.careService.CareService1Soap.GetCareCenterKiddiesDetailsAsync(CareWebClient.careService.GetCareCenterKiddiesDetailsRequest request) {
            return base.Channel.GetCareCenterKiddiesDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterKiddiesDetailsResponse> GetCareCenterKiddiesDetailsAsync(System.Guid centerId) {
            CareWebClient.careService.GetCareCenterKiddiesDetailsRequest inValue = new CareWebClient.careService.GetCareCenterKiddiesDetailsRequest();
            inValue.Body = new CareWebClient.careService.GetCareCenterKiddiesDetailsRequestBody();
            inValue.Body.centerId = centerId;
            return ((CareWebClient.careService.CareService1Soap)(this)).GetCareCenterKiddiesDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.GetCareCenterStaffsDetailsResponse CareWebClient.careService.CareService1Soap.GetCareCenterStaffsDetails(CareWebClient.careService.GetCareCenterStaffsDetailsRequest request) {
            return base.Channel.GetCareCenterStaffsDetails(request);
        }
        
        public CareWebClient.careService.Staffs[] GetCareCenterStaffsDetails(System.Guid centerId) {
            CareWebClient.careService.GetCareCenterStaffsDetailsRequest inValue = new CareWebClient.careService.GetCareCenterStaffsDetailsRequest();
            inValue.Body = new CareWebClient.careService.GetCareCenterStaffsDetailsRequestBody();
            inValue.Body.centerId = centerId;
            CareWebClient.careService.GetCareCenterStaffsDetailsResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).GetCareCenterStaffsDetails(inValue);
            return retVal.Body.GetCareCenterStaffsDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterStaffsDetailsResponse> CareWebClient.careService.CareService1Soap.GetCareCenterStaffsDetailsAsync(CareWebClient.careService.GetCareCenterStaffsDetailsRequest request) {
            return base.Channel.GetCareCenterStaffsDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.GetCareCenterStaffsDetailsResponse> GetCareCenterStaffsDetailsAsync(System.Guid centerId) {
            CareWebClient.careService.GetCareCenterStaffsDetailsRequest inValue = new CareWebClient.careService.GetCareCenterStaffsDetailsRequest();
            inValue.Body = new CareWebClient.careService.GetCareCenterStaffsDetailsRequestBody();
            inValue.Body.centerId = centerId;
            return ((CareWebClient.careService.CareService1Soap)(this)).GetCareCenterStaffsDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CareWebClient.careService.AuthenticateUserAppResponse CareWebClient.careService.CareService1Soap.AuthenticateUserApp(CareWebClient.careService.AuthenticateUserAppRequest request) {
            return base.Channel.AuthenticateUserApp(request);
        }
        
        public void AuthenticateUserApp(string name, string password, string type) {
            CareWebClient.careService.AuthenticateUserAppRequest inValue = new CareWebClient.careService.AuthenticateUserAppRequest();
            inValue.Body = new CareWebClient.careService.AuthenticateUserAppRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            inValue.Body.type = type;
            CareWebClient.careService.AuthenticateUserAppResponse retVal = ((CareWebClient.careService.CareService1Soap)(this)).AuthenticateUserApp(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserAppResponse> CareWebClient.careService.CareService1Soap.AuthenticateUserAppAsync(CareWebClient.careService.AuthenticateUserAppRequest request) {
            return base.Channel.AuthenticateUserAppAsync(request);
        }
        
        public System.Threading.Tasks.Task<CareWebClient.careService.AuthenticateUserAppResponse> AuthenticateUserAppAsync(string name, string password, string type) {
            CareWebClient.careService.AuthenticateUserAppRequest inValue = new CareWebClient.careService.AuthenticateUserAppRequest();
            inValue.Body = new CareWebClient.careService.AuthenticateUserAppRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            inValue.Body.type = type;
            return ((CareWebClient.careService.CareService1Soap)(this)).AuthenticateUserAppAsync(inValue);
        }
    }
}
