//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_setup_tab
    {
        public care_center_setup_tab()
        {
            this.care_center_bookeeping = new HashSet<care_center_bookeeping>();
            this.care_center_log = new HashSet<care_center_log>();
            this.care_center_social_media = new HashSet<care_center_social_media>();
            this.care_center_subscription_details_table = new HashSet<care_center_subscription_details_table>();
            this.care_setup_photos = new HashSet<care_setup_photos>();
            this.care_center_kiddies = new HashSet<care_center_kiddies>();
            this.care_center_staffs = new HashSet<care_center_staffs>();
        }
    
        public System.Guid care_center_id { get; set; }
        public string care_center_login_name { get; set; }
        public string care_center_name { get; set; }
        public string care_center_location { get; set; }
        public Nullable<bool> care_center_subscription_status { get; set; }
        public string care_center_password { get; set; }
        public Nullable<System.DateTime> care_center_date_registered { get; set; }
        public Nullable<bool> care_center_activate_deactivate { get; set; }
        public string care_center_staff_strength { get; set; }
        public Nullable<System.Guid> care_center_folder_id { get; set; }
        public string care_center_email { get; set; }
        public string care_center_contact_number { get; set; }
        public string care_center_website { get; set; }
        public string care_center_image_path { get; set; }
    
        public virtual ICollection<care_center_bookeeping> care_center_bookeeping { get; set; }
        public virtual ICollection<care_center_log> care_center_log { get; set; }
        public virtual ICollection<care_center_social_media> care_center_social_media { get; set; }
        public virtual ICollection<care_center_subscription_details_table> care_center_subscription_details_table { get; set; }
        public virtual ICollection<care_setup_photos> care_setup_photos { get; set; }
        public virtual ICollection<care_center_kiddies> care_center_kiddies { get; set; }
        public virtual ICollection<care_center_staffs> care_center_staffs { get; set; }
    }
}
