//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_subscription_features
    {
        public System.Guid subscription_features_id { get; set; }
        public System.Guid subscription_type_id { get; set; }
        public string subscription_features_description { get; set; }
    
        public virtual care_center_subscription_type care_center_subscription_type { get; set; }
    }
}
