//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_activity_setup
    {
        public care_center_activity_setup()
        {
            this.care_center_kiddies_activity = new HashSet<care_center_kiddies_activity>();
        }
    
        public System.Guid care_center_activity_id { get; set; }
        public string care_center_activity_title { get; set; }
        public string care_center_activity_details { get; set; }
        public string care_center_activity_icon_path { get; set; }
    
        public virtual ICollection<care_center_kiddies_activity> care_center_kiddies_activity { get; set; }
    }
}
