//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_kiddies_activity
    {
        public System.Guid care_center_kiddies_activity_id { get; set; }
        public Nullable<System.Guid> care_center_activity_id { get; set; }
        public string care_center_kiddies_activity_notes { get; set; }
        public string care_center_kiddies_activity_image_path { get; set; }
        public Nullable<System.DateTime> care_center_kiddies_activity_date_updated { get; set; }
        public Nullable<System.Guid> care_kiddie_id { get; set; }
        public string care_center_kiddies_activity_video_path { get; set; }
        public Nullable<bool> care_center_kiddies_activity_media_type { get; set; }
    
        public virtual care_center_activity_setup care_center_activity_setup { get; set; }
        public virtual care_center_kiddies care_center_kiddies { get; set; }
    }
}
