//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_invoice
    {
        public System.Guid care_center_invoice_id { get; set; }
        public Nullable<System.Guid> care_kiddie_id { get; set; }
        public Nullable<System.Guid> care_center_book_keeping_details_id { get; set; }
        public string receipt_no { get; set; }
        public string payment_type { get; set; }
        public Nullable<decimal> payment_made { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    
        public virtual care_center_bookeeping_details care_center_bookeeping_details { get; set; }
        public virtual care_center_kiddies care_center_kiddies { get; set; }
    }
}
