//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_bookeeping_details
    {
        public care_center_bookeeping_details()
        {
            this.care_center_invoice = new HashSet<care_center_invoice>();
        }
    
        public System.Guid care_center_book_keeping_details_id { get; set; }
        public Nullable<System.Guid> care_center_bookeeping_id { get; set; }
        public string payment_description { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
    
        public virtual care_center_bookeeping care_center_bookeeping { get; set; }
        public virtual ICollection<care_center_invoice> care_center_invoice { get; set; }
    }
}
