//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_subscription_details_table
    {
        public System.Guid care_center_subscription_details_id { get; set; }
        public Nullable<System.Guid> subscription_type_id { get; set; }
        public Nullable<System.DateTime> subscription_start_date { get; set; }
        public Nullable<System.DateTime> subscription_end_date { get; set; }
        public Nullable<decimal> subscription_value { get; set; }
        public string subscription_note { get; set; }
        public Nullable<System.Guid> care_center_id { get; set; }
    
        public virtual care_center_subscription_type care_center_subscription_type { get; set; }
        public virtual care_center_setup_tab care_center_setup_tab { get; set; }
    }
}
