//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_staffs
    {
        public System.Guid care_staff_id { get; set; }
        public string care_staff_login_name { get; set; }
        public string care_staff_password { get; set; }
        public string care_staff_gender { get; set; }
        public Nullable<System.Guid> care_center_id { get; set; }
        public string care_staff_name { get; set; }
        public string care_staff_contact_number { get; set; }
        public string care_staff_ratings { get; set; }
        public Nullable<System.DateTime> care_staff_date_registered { get; set; }
        public Nullable<bool> care_staff_employment_status { get; set; }
        public string care_staff_email { get; set; }
    
        public virtual care_center_setup_tab care_center_setup_tab { get; set; }
    }
}
