//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareDBEntities1 : DbContext
    {
        public CareDBEntities1()
            : base("name=CareDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<care_center_bookeeping> care_center_bookeeping { get; set; }
        public DbSet<care_center_social_media> care_center_social_media { get; set; }
        public DbSet<care_center_subscription_details_table> care_center_subscription_details_table { get; set; }
        public DbSet<care_center_subscription_features> care_center_subscription_features { get; set; }
        public DbSet<care_center_subscription_type> care_center_subscription_type { get; set; }
        public DbSet<care_center_log> care_center_log { get; set; }
        public DbSet<care_center_bookeeping_details> care_center_bookeeping_details { get; set; }
        public DbSet<care_setup_photos> care_setup_photos { get; set; }
        public DbSet<care_center_activity_setup> care_center_activity_setup { get; set; }
        public DbSet<care_center_kiddies_activity> care_center_kiddies_activity { get; set; }
        public DbSet<care_center_parents> care_center_parents { get; set; }
        public DbSet<care_photo_details> care_photo_details { get; set; }
        public DbSet<care_center_invoice> care_center_invoice { get; set; }
        public DbSet<care_center_setup_tab> care_center_setup_tab { get; set; }
        public DbSet<care_center_kiddies> care_center_kiddies { get; set; }
        public DbSet<care_center_staffs> care_center_staffs { get; set; }
    }
}
