//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace careServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class care_center_parents
    {
        public care_center_parents()
        {
            this.care_center_kiddies = new HashSet<care_center_kiddies>();
        }
    
        public System.Guid care_parent_id { get; set; }
        public string care_parent_login_id { get; set; }
        public string care_parent_login_password { get; set; }
        public string care_parent_full_name { get; set; }
        public string care_parent_contact_phone { get; set; }
        public string care_parent_contact_email { get; set; }
        public string care_parent_occupation { get; set; }
    
        public virtual ICollection<care_center_kiddies> care_center_kiddies { get; set; }
    }
}
